### ISSUE TITLE
add ViewNote action with x-success optional parameter

### ISSUE THREAD

**Issue by crarau** [evernote/evernote-ios-x-callback-url#1]
Add action for viewing a note in Evernote.
The option x-callback parameters (x-success, x-cancel, x-error) should also be working

The desired functionality is to view a note in Evernote and when you press Done to come back to the calling app.

**Comment by everic** [comment]
Fixed by https://github.com/evernote/evernote-cloud-sdk-ios/commit/8d4c12f5372ecf58ef3d09993e1533d6e7878b6a

You can test with the App Store version of Evernote app, should be working already.
